config/routes.rb
Rails.application.routes.draw do
  get "products", to: "products#index"
  get "products.id", to: "products#show"
  resources :products, only: [:index, :show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :price, :stock_quantity, presence: true
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @products = Product.includes(:category).all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Simple Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>All Products</h1>

<ul>
    <% @products.each do |product| %>
        <li>
            <strong>Title:</strong> <%= link_to product.title, product_path(product)%><br>
            <strong>Price:</strong> $<%= product.price %><br>
            <strong>Stock Quantity:</strong> <%= product.stock_quantity %><br>
            <strong>Category:</strong> <%= product.category.name %>
        </li>
  <% end %>
</ul>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p>Description: <%= @product.description %></p>
<p>Price: $<%= @product.price %></p>
<p>Stock Quantity: <%= @product.stock_quantity %></p>
<p>Category <%= @product.category.name %></p>
<%= link_to 'Back to Products', products_path %>